[general]
copy-command = "wl-copy"
focus-toggles-toolbars= true
initial-tool = "brush"
zoom-factor=1.1
actions-on-right-click = ["save-to-clipboard"]
[font]
family = "Noto Sans"
style = "Regular"
fallback = [
    "Noto Sans CJK SC",
    "Noto Sans CJK JP",
    "Noto Sans CJK TC",
    "Noto Sans CJK KR"
]
